#! /usr/bin/env python3

####################################################################################################

####################################################################################################
#
# SnowAvalancheData - 
# Copyright (C) 2021 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
####################################################################################################

from pathlib import Path
from pprint import pprint

from SnowAvalancheData.Import.Anena import AccidentBook, AccidentRegister, Accident

####################################################################################################

xls_paths = Path('data').joinpath('anena-xls').glob('tableau-accidents-*-*.xls')
xls_paths = sorted(xls_paths)

if False:
    for path in xls_paths[:-1]:
        book = AccidentBook(path)
        Accident.learn(book[0])
    Accident.dump()

if True:
    accidents = AccidentRegister()
    for path in xls_paths:
        book = AccidentBook(path)
        if book.start_year < 2019:
            print(f'Load {path}')
            accidents += book.to_accident_pre_2019()
    path = Path('anena-accidents.json')
    print(f'Write {path}')
    accidents.write_json(path)
