#! /usr/bin/env python3

####################################################################################################

####################################################################################################
#
# SnowAvalancheData - 
# Copyright (C) 2021 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
####################################################################################################

from pathlib import Path

# https://pandas.pydata.org
import pandas as pd

####################################################################################################

path = Path('data', 'anena-xls', 'tableau-accidents-2010-2011.xls')
sheet = pd.read_excel(path)
sheet.info()

sheet.to_json(orient="records", force_ascii=False)

# Select a column
sheet['date']
# Select a row
sheet.iloc[0]

# Concat sheets
# pd.concat([...], axis=0)
